// ========== PRODUCTS DATA ==========
const products = [
  // ===== APPLE iPhones =====
  {
    id: 1, 
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    price: 94000, 
    oldPrice: 100000, 
    image: "images/Apple/iPhone-17-Pro-Max2.webp",
    specs: ["A19 Pro", "12GB RAM", "256GB", "5G"], 
    badge: "New", 
    badgeType: "new", 
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A19 Pro Bionic",
    ram: "12GB",
    storage: "256GB / 512GB / 1TB /2TB",
    network: "5G",
    screen: "6.9\" Super Retina XDR OLED",
    battery: "4832mAh /5088mAh",
    camera: "48MP + 48MP + 48MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 26"
  },
    colors: ["Cosmic Orange", "Deep Blue", "Silver"],
    description: "iPhone 17 Pro Max is the most powerful and intelligent phone from Apple. With the revolutionary A17 Pro chip, 48MP camera, and titanium design, it delivers an exceptional performance and photography experience.",
    rating: 4.8,
    reviews: 156,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 2,
    name: "iPhone 17 Pro",
    brand: "Apple",
    price: 85999,
    oldPrice: 92999,
    image: "images/Apple/iPhone-17-Pro2.webp",
    specs: ["A19 Pro", "12GB RAM", "256GB", "5G", "Wi-Fi 7"],
    badge: "new",
    badgeType: "new",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A19 Pro Bionic (3nm)",
    ram: "12GB",
    storage: "256GB / 512GB / 1TB / 2TB",
    network: "5G / Wi-Fi 7",
    screen: "6.3\" LTPO Super Retina XDR OLED (120Hz)",
    battery: "3988-4252mAh (Expected)",
    camera: "48MP + 48MP + 48MP (Quad-Camera System)",
    frontCamera: "18MP TrueDepth",
    os: "iOS 26"
  },
    colors: ["Cosmic Black", "Arctic White", "Ultramarine Blue", "Natural Titanium"],
    description: "The next generation of Apple's Pro phones. Features the new A19 Pro chip, a refined design, a massive camera upgrade with 48MP across all lenses, and higher RAM capacity.",
    rating: 4.0,
    reviews: 0,
    inStock: false,
    delivery: "Currently Unavailable",
    freeShipping: true
  },
  {
    id: 3,
    name: "iPhone 17",
    brand: "Apple",
    price: 52999,
    oldPrice: 59999,
    image: "images/Apple/iPhone-17.webp",
    specs: ["A19", "8GB RAM", "256GB", "5G"],
    badge: "new",
    badgeType: "new",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A19 Bionic (3nm)",
    ram: "8GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.3\" LTPO Super Retina XDR OLED (120Hz)",
    battery: "3692mAh (Expected)",
    camera: "48MP (Wide) + 48MP (Ultra Wide)",
    frontCamera: "18MP TrueDepth",
    os: "iOS 26"
  },
    colors: ["Black", "White", "Mist Blue", "Sage", "Lavender"],
    description: "A comprehensive refresh of the base iPhone series. It offers a slightly larger screen and 120Hz refresh rate for the first time in the regular lineup, along with the A19 chip and an improved GPU.",
    rating: 4.0,
    reviews: 0,
    inStock: false,
    delivery: "Currently Unavailable",
    freeShipping: true
  },
  {
    id: 4,
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    price: 78999,
    oldPrice: 85999,
    image: "images/Apple/Apple-iPhone-16-Pro-Max.webp",
    specs: ["A18 Pro", "8GB RAM", "256GB", "5G", "Wi-Fi 7"],
    badge: "New ",
    badgeType: "new",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A18 Pro Bionic (3nm)",
    ram: "8GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G / Wi-Fi 7",
    screen: "6.9\" LTPO Super Retina XDR OLED (120Hz)",
    battery: "4685mAh (Expected)",
    camera: "48MP + 12MP (Telephoto 5X) + 48MP (Ultra Wide)",
    frontCamera: "12MP TrueDepth",
    os: "iOS 18"
  },
    colors: ["Titanium Black", "Titanium White", "Titanium Blue", "Natural Titanium", "Desert Titanium"],
    description: "Apple's largest phone yet with a 6.9-inch screen. Features the A18 Pro chip, which is optimized for AI, and an advanced 5X Telephoto zoom camera.",
    rating: 3.8,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 5,
    name: "iPhone 16 Pro",
    brand: "Apple",
    price: 68999,
    oldPrice: 75999,
    image: "images/Apple/iphone-16-pro-2.webp",
    specs: ["A18 Pro", "8GB RAM", "128GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A18 Pro Bionic (3nm)",
    ram: "8GB",
    storage: "128GB / 256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.3\" LTPO Super Retina XDR OLED (120Hz)",
    battery: "3528mAh (Expected)",
    camera: "48MP + 12MP (Telephoto 5X) + 48MP (Ultra Wide)",
    frontCamera: "12MP TrueDepth",
    os: "iOS 18"
  },
    colors: ["Titanium Black", "Titanium White", "Natural Titanium", "Rose Titanium"],
    description: "The Pro version features a slightly larger 6.3-inch size for the first time. It includes the same 5X Telephoto camera capabilities as the Pro Max model and the powerful A18 Pro chip.",
    rating: 3.7,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 6,
    name: "iPhone 16",
    brand: "Apple",
    price: 48999,
    oldPrice: 55999,
    image: "images/Apple/iPhone-16-1.webp",
    specs: ["A18", "8GB RAM", "128GB", "5G"],
    badge: "New ",
    badgeType: "new",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A18 Bionic (3nm)",
    ram: "8GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.1\" Super Retina XDR OLED",
    battery: "3561mAh (Expected)",
    camera: "48MP (Wide) + 12MP (Ultra Wide)",
    frontCamera: "12MP TrueDepth",
    os: "iOS 18"
    },
    colors: ["Black", "White", "Pink", "Teal", "Ultramarine"],
    description: "The base model with significant performance improvements due to the new A18 chip, an upgraded 48MP main camera, and the addition of the new Action Button.",
    rating: 3.0,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 7, 
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    price: 65999, 
    oldPrice: 72999, 
    image: "images/Apple/iPhone-15-Pro-Max-2.webp",
    specs: ["A17 Pro", "8GB RAM", "256GB", "5G"], 
    badge: "New", 
    badgeType: "new", 
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A17 Pro Bionic",
    ram: "8GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.7\" Super Retina XDR OLED",
    battery: "4422mAh",
    camera: "48MP + 12MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 17"
  },
    colors: ["Titanium Black", "Titanium White", "Titanium Blue", "Natural Titanium"],
    description: "iPhone 15 Pro Max is the most powerful and intelligent phone from Apple. With the revolutionary A17 Pro chip, 48MP camera, and titanium design, it delivers an exceptional performance and photography experience.",
    rating: 4.8,
    reviews: 156,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 8,
    name: "iPhone 15 Pro",
    brand: "Apple",
    price: 58999,
    oldPrice: 64999,
    image: "images/Apple/iPhone-15-Pro-2.webp",
    specs: ["A17 Pro", "8GB RAM", "128GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A17 Pro Bionic",
    ram: "8GB",
    storage: "128GB / 256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.1\" Super Retina XDR OLED",
    battery: "3274mAh",
    camera: "48MP + 12MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 17"
  },
    colors: ["Black Titanium", "White Titanium", "Blue Titanium", "Natural Titanium"],
    description: "iPhone 15 Pro features the powerful A17 Pro chip, a durable titanium design, and a stunning 48MP camera system. It offers exceptional performance in a compact Pro design.",
    rating: 4.5, 
    reviews: 0, 
    inStock: true, 
    delivery: "2-3 Days", 
    freeShipping: true 
  },
  {
    id: 9,
    name: "iPhone 15 Plus",
    brand: "Apple",
    price: 52999,
    oldPrice: 58999,
    image: "images/Apple/iPhone-15-Plus-2.webp",
    specs: ["A16 Bionic", "6GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A16 Bionic",
    ram: "6GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.7\" Super Retina XDR OLED",
    battery: "4383mAh",
    camera: "48MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 17"
  },
    colors: ["Black", "Blue", "Green", "Yellow", "Pink"],
    description: "The iPhone 15 Plus offers the powerful A16 Bionic chip and a large 6.7-inch display, perfect for users who want a big screen and great battery life.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 10,
    name: "iPhone 15",
    brand: "Apple",
    price: 46999,
    oldPrice: 51999,
    image: "images/Apple/iPhone-15-3.webp",
    specs: ["A16 Bionic", "6GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A16 Bionic",
    ram: "6GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.1\" Super Retina XDR OLED",
    battery: "3349mAh",
    camera: "48MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 17"
  },
    colors: ["Black", "Blue", "Green", "Yellow", "Pink"],
    description: "The standard iPhone 15 brings the A16 Bionic chip and a new 48MP main camera, offering a significant upgrade in performance and photography.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 11,
    name: "iPhone 14 Pro Max",
    brand: "Apple",
    price: 52999,
    oldPrice: 62999,
    image: "images/Apple/Apple-iPhone-14-Pro-Max.webp",
    specs: ["A16 Bionic", "6GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A16 Bionic",
    ram: "6GB",
    storage: "128GB / 256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.7\" Super Retina XDR OLED",
    battery: "4323mAh",
    camera: "48MP + 12MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 16"
  },
    colors: ["Space Black", "Silver", "Gold", "Deep Purple"],
    description: "iPhone 14 Pro Max features the Dynamic Island, the A16 Bionic chip, and a ProMotion display, delivering a high-end mobile experience.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 12,
    name: "iPhone 14 Pro",
    brand: "Apple",
    price: 46999,
    oldPrice: 54999,
    image: "images/Apple/Apple-iPhone-14-Pro.webp",
    specs: ["A16 Bionic", "6GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A16 Bionic",
    ram: "6GB",
    storage: "128GB / 256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.1\" Super Retina XDR OLED",
    battery: "3200mAh",
    camera: "48MP + 12MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 16"
  },
    colors: ["Space Black", "Silver", "Gold", "Deep Purple"],
    description: "iPhone 14 Pro brings the Dynamic Island and A16 Bionic performance to a comfortable 6.1-inch form factor.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 13,
    name: "iPhone 14 Plus",
    brand: "Apple",
    price: 42999,
    oldPrice: 49999,
    image: "images/Apple/Apple-iPhone-14-Plus.webp",
    specs: ["A15 Bionic", "6GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A15 Bionic",
    ram: "6GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.7\" Super Retina XDR OLED",
    battery: "4325mAh",
    camera: "12MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 16"
  },
    colors: ["Midnight", "Starlight", "Blue", "Purple", "Red"],
    description: "The iPhone 14 Plus offers a large 6.7-inch display and excellent battery life, powered by the reliable A15 Bionic chip.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 14,
    name: "iPhone 14",
    brand: "Apple",
    price: 38999,
    oldPrice: 44999,
    image: "images/Apple/Apple-iPhone-14.webp",
    specs: ["A15 Bionic", "6GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A15 Bionic",
    ram: "6GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.1\" Super Retina XDR OLED",
    battery: "3279mAh",
    camera: "12MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 16"
  },
    colors: ["Midnight", "Starlight", "Blue", "Purple", "Red"],
    description: "The standard iPhone 14, a great all-around phone with the A15 Bionic chip and an advanced dual-camera system.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 15,
    name: "iPhone 13",
    brand: "Apple",
    price: 32999,
    oldPrice: 38999,
    image: "images/Apple/IPhone-13.webp",
    specs: ["A15 Bionic", "4GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A15 Bionic",
    ram: "4GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.1\" Super Retina XDR OLED",
    battery: "3240mAh",
    camera: "12MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 15"
  },
    colors: ["Starlight", "Midnight", "Blue", "Pink", "Red"],
    description: "iPhone 13 provides excellent performance with the A15 Bionic chip and a bright Super Retina XDR display.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 16,
    name: "iPhone 12",
    brand: "Apple",
    price: 26999,
    oldPrice: 32999,
    image: "images/Apple/Apple-iPhone-12.webp",
    specs: ["A14 Bionic", "4GB RAM", "64GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A14 Bionic",
    ram: "4GB",
    storage: "64GB / 128GB / 256GB",
    network: "5G",
    screen: "6.1\" Super Retina XDR OLED",
    battery: "2815mAh",
    camera: "12MP + 12MP",
    frontCamera: "12MP TrueDepth",
    os: "iOS 14"
  },
    colors: ["Black", "White", "Red", "Green", "Blue", "Purple"],
    description: "iPhone 12 offers a great value with the A14 Bionic chip and 5G connectivity.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 17,
    name: "iPhone SE (2022)",
    brand: "Apple",
    price: 21999,
    oldPrice: 26999,
    image: "images/Apple/Apple-iPhone-11.webp",
    specs: ["A15 Bionic", "4GB RAM", "64GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "apple",
    //Details:
    detailedSpecs: {
    processor: "A15 Bionic",
    ram: "4GB",
    storage: "64GB / 128GB / 256GB",
    network: "5G",
    screen: "4.7\" Retina HD IPS LCD",
    battery: "2018mAh",
    camera: "12MP Single",
    frontCamera: "7MP",
    os: "iOS 15"
  },
    colors: ["Midnight", "Starlight", "Red"],
    description: "The iPhone SE (2022) combines the compact design of the classic iPhone with the powerful A15 Bionic chip and 5G.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },

  // ===== SAMSUNG Galaxy =====
  {
    id: 18,
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 59999,
    oldPrice: 68999,
    image: "images/samsung/Samsung-Galaxy-S24-Ultra-5G.webp",
    specs: ["Snapdragon 8 Gen 3", "12GB RAM", "256GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 3 for Galaxy",
    ram: "12GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.8\" Dynamic AMOLED 2X",
    battery: "5000mAh",
    camera: "200MP + 50MP + 10MP + 12MP",
    frontCamera: "12MP",
    os: "Android 14 / One UI 6.1"
  },
    colors: ["Titanium Black", "Titanium Gray", "Titanium Violet", "Titanium Yellow"],
    description: "The Samsung Galaxy S24 Ultra is the ultimate flagship with a powerful Snapdragon 8 Gen 3 chip, a 200MP camera, and built-in S Pen.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 19,
    name: "Samsung Galaxy S24 plus",
    brand: "Samsung",
    price: 48999,
    oldPrice: 56999,
    image: "images/samsung/Samsung-Galaxy-S24-Plus-5G.webp",
    specs: ["Exynos 2400", "12GB RAM", "256GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Exynos 2400",
    ram: "12GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.7\" Dynamic AMOLED 2X",
    battery: "4900mAh",
    camera: "50MP + 10MP + 12MP",
    frontCamera: "12MP",
    os: "Android 14 / One UI 6.1"
  },
    colors: ["Onyx Black", "Marble Gray", "Cobalt Violet", "Amber Yellow"],
    description: "Galaxy S24+ combines a large screen and all-day battery life with the high-performance Exynos 2400 chip and Galaxy AI features.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 20,
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    price: 42999,
    oldPrice: 49999,
    image: "images/samsung/Samsung-Galaxy-S23-5G.webp",
    specs: ["Exynos 2400", "8GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Exynos 2400",
    ram: "8GB",
    storage: "128GB / 256GB",
    network: "5G",
    screen: "6.2\" Dynamic AMOLED 2X",
    battery: "4000mAh",
    camera: "50MP + 10MP + 12MP",
    frontCamera: "12MP",
    os: "Android 14 / One UI 6.1"
  },
    colors: ["Onyx Black", "Marble Gray", "Cobalt Violet", "Amber Yellow"],
    description: "The Galaxy S24 offers a compact design without compromising on power, featuring the Exynos 2400 and AI capabilities.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 21,
    name: "Samsung Galaxy S23 Ultra",
    brand: "Samsung",
    price: 48999,
    oldPrice: 58999,
    image: "images/samsung/Samsung-Galaxy-S23-Ultra-5G.webp",
    specs: ["Snapdragon 8 Gen 2", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 2 for Galaxy",
    ram: "12GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.8\" Dynamic AMOLED 2X",
    battery: "5000mAh",
    camera: "200MP + 10MP + 10MP + 12MP",
    frontCamera: "12MP",
    os: "Android 13 / One UI 5.1"
  },
    colors: ["Phantom Black", "Cream", "Green", "Lavender"],
    description: "Galaxy S23 Ultra features the powerful Snapdragon 8 Gen 2, a stunning 200MP camera, and a dedicated S Pen for maximum productivity.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 22,
    name: "Samsung Galaxy S23",
    brand: "Samsung",
    price: 34999,
    oldPrice: 42999,
    image: "images/samsung/Samsung-Galaxy-S23-5G (1).webp",
    specs: ["Snapdragon 8 Gen 2", "8GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 2 for Galaxy",
    ram: "8GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.1\" Dynamic AMOLED 2X",
    battery: "3900mAh",
    camera: "50MP + 10MP + 12MP",
    frontCamera: "12MP",
    os: "Android 13 / One UI 5.1"
  },
    colors: ["Phantom Black", "Cream", "Green", "Lavender"],
    description: "The compact Galaxy S23 offers flagship performance with the Snapdragon 8 Gen 2 chip and a premium camera system.",
  rating: 4.5,
  reviews: 0,
  inStock: true,
  delivery: "2-3 Days",
  freeShipping: true
  },
  {
    id: 23,
    name: "Samsung Galaxy Z Fold 5",
    brand: "Samsung",
    price: 82999,
    oldPrice: null,
    image: "images/samsung/samsung-galaxy-z-fold5-3.webp",
    specs: ["Snapdragon 8 Gen 2", "12GB RAM", "256GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 2 for Galaxy",
    ram: "12GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "7.6\" Foldable AMOLED / 6.2\" Cover",
    battery: "4400mAh",
    camera: "50MP + 10MP + 12MP",
    frontCamera: "10MP Cover / 4MP Under Display",
    os: "Android 13 / One UI 5.1"
  },
    colors: ["Icy Blue", "Phantom Black", "Cream"],
    description: "Galaxy Z Fold 5 is the ultimate foldable experience, featuring a refined design, powerful performance, and a large tablet-like screen.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 24,
    name: "Samsung Galaxy Z Flip 5",
    brand: "Samsung",
    price: 52999,
    oldPrice: null,
    image: "images/samsung/samsung-z-flip5-3.webp",
    specs: ["Snapdragon 8 Gen 2", "8GB RAM", "256GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 2 for Galaxy",
    ram: "8GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.7\" Foldable AMOLED / 3.4\" Cover",
    battery: "3700mAh",
    camera: "12MP + 12MP",
    frontCamera: "10MP",
    os: "Android 13 / One UI 5.1"
  },
    colors: ["Mint", "Graphite", "Cream", "Lavender"],
    description: "Galaxy Z Flip 5 is a stylish compact foldable with an expressive 3.4-inch cover screen and the powerful Snapdragon 8 Gen 2.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 25,
    name: "Samsung Galaxy A54",
    brand: "Samsung",
    price: 18999,
    oldPrice: 22999,
    image: "images/samsung/Samsung-Galaxy-A54-5G.webp",
    specs: ["Exynos 1380", "8GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Exynos 1380",
    ram: "8GB",
    storage: "128GB / 256GB",
    network: "5G",
    screen: "6.4\" Super AMOLED",
    battery: "5000mAh",
    camera: "50MP + 12MP + 5MP",
    frontCamera: "32MP",
    os: "Android 13 / One UI 5.1"
  },
    colors: ["Awesome Black", "Awesome White", "Awesome Violet", "Awesome Lime"],
    description: "The Galaxy A54 is a strong mid-range contender with 5G, a beautiful Super AMOLED display, and a long-lasting 5000mAh battery.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 26,
    name: "Samsung Galaxy A34",
    brand: "Samsung",
    price: 14999,
    oldPrice: 17999,
    image: "images/samsung/Samsung-Galaxy-A34-5G.webp",
    specs: ["Dimensity 1080", "8GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 1080",
    ram: "8GB",
    storage: "128GB / 256GB",
    network: "5G",
    screen: "6.6\" Super AMOLED",
    battery: "5000mAh",
    camera: "48MP + 8MP + 5MP",
    frontCamera: "13MP",
    os: "Android 13 / One UI 5.1"
  },
    colors: ["Awesome Lime", "Awesome Silver", "Awesome Violet", "Awesome Graphite"],
    description: "Galaxy A34 offers reliable 5G performance and a large, vibrant Super AMOLED screen at an affordable price point.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 27,
    name: "Samsung Galaxy A24",
    brand: "Samsung",
    price: 10999,
    oldPrice: 12999,
    image: "images/samsung/Samsung-Galaxy-A24-4G.webp ",
    specs: ["Helio G99", "6GB RAM", "128GB", "4G"],
    badge: "Sale",
    badgeType: "sale",
    category: "samsung",
    //Details:
    detailedSpecs: {
    processor: "Helio G99",
    ram: "6GB",
    storage: "128GB",
    network: "4G",
    screen: "6.5\" Super AMOLED",
    battery: "5000mAh",
    camera: "50MP + 5MP + 2MP",
    frontCamera: "13MP",
    os: "Android 13 / One UI 5.1"
  },
    colors: ["Black", "Silver", "Burgundy", "Green"],
    description: "The Galaxy A24 is an affordable option with a large 6.5\" Super AMOLED screen and a huge 5000mAh battery for extended use.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },

  // ===== XIAOMI =====
  {
    id: 28,
    name: "Xiaomi 14 Pro",
    brand: "Xiaomi",
    price: 42999,
    oldPrice: 49999,
    image: "images/Xiaomi/Xiaomi-14-Pro-1.webp",
    specs: ["Snapdragon 8 Gen 3", "12GB RAM", "256GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "xiaomi",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 3",
    ram: "12GB / 16GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.73\" LTPO AMOLED",
    battery: "4880mAh",
    camera: "50MP + 50MP + 50MP",
    frontCamera: "32MP",
    os: "Android 14 / HyperOS"
  },
    colors: ["Black", "Silver", "Titanium", "Green"],
    description: "Xiaomi 14 Pro is a high-end flagship featuring the powerful Snapdragon 8 Gen 3 and a triple 50MP Leica-tuned camera system.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 29,
    name: "Xiaomi 14",
    brand: "Xiaomi",
    price: 36999,
    oldPrice: 42999,
    image: "images/Xiaomi/Xiaomi-14-1.webp",
    specs: ["Snapdragon 8 Gen 3", "12GB RAM", "256GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "xiaomi",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 3",
    ram: "8GB / 12GB / 16GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.36\" LTPO AMOLED",
    battery: "4610mAh",
    camera: "50MP + 50MP + 50MP",
    frontCamera: "32MP",
    os: "Android 14 / HyperOS"
  },
    colors: ["Black", "White", "Green", "Pink"],
    description: "Xiaomi 14 delivers flagship performance in a compact body, powered by the Snapdragon 8 Gen 3 chip and Leica cameras.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 30,
    name: "Xiaomi 13T Pro",
    brand: "Xiaomi",
    price: 28999,
    oldPrice: 34999,
    image: "images/Xiaomi/Xiaomi-13T-Pro-1.webp",
    specs: ["Dimensity 9200+", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "xiaomi",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 9200+",
    ram: "12GB / 16GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.67\" AMOLED",
    battery: "5000mAh",
    camera: "50MP + 12MP + 50MP",
    frontCamera: "20MP",
    os: "Android 13 / MIUI 14"
  },
    colors: ["Black", "Green", "Blue"],
    description: "Xiaomi 13T Pro offers top-tier performance with the Dimensity 9200+ processor and 120W fast charging.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 31,
    name: "Xiaomi 13 Pro",
    brand: "Xiaomi",
    price: 32999,
    oldPrice: 39999,
    image: "images/Xiaomi/Xiaomi-13-Pro-1.webp",
    specs: ["Snapdragon 8 Gen 2", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "xiaomi",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 2",
    ram: "8GB / 12GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.73\" LTPO AMOLED",
    battery: "4820mAh",
    camera: "50MP + 50MP + 50MP",
    frontCamera: "32MP",
    os: "Android 13 / MIUI 14"
  },
    colors: ["Black", "White", "Green", "Blue"],
    description: "Xiaomi 13 Pro is a photography beast with 1-inch sensor and Snapdragon 8 Gen 2 power.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 32,
    name: "Xiaomi 13",
    brand: "Xiaomi",
    price: 26999,
    oldPrice: 32999,
    image: "images/Xiaomi/Xiaomi-13-1.webp",
    specs: ["Snapdragon 8 Gen 2", "8GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "xiaomi",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 2",
    ram: "8GB / 12GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.36\" AMOLED",
    battery: "4500mAh",
    camera: "50MP + 10MP + 12MP",
    frontCamera: "32MP",
    os: "Android 13 / MIUI 14"
  },
    colors: ["Black", "White", "Green", "Blue"],
    description: "Xiaomi 13 is a compact flagship with powerful Snapdragon 8 Gen 2 performance and high-quality cameras.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days", 
    freeShipping: true 
  },
  {
    id: 33,
    name: "Redmi Note 13 Pro+",
    brand: "Xiaomi",
    price: 18999,
    oldPrice: 22999,
    image: "images/Xiaomi/Xiaomi-Redmi-Note-13-Pro-Plus.webp",
    specs: ["Dimensity 7200 Ultra", "12GB RAM", "512GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "xiaomi",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 7200 Ultra",
    ram: "8GB / 12GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.67\" AMOLED",
    battery: "5000mAh",
    camera: "200MP + 8MP + 2MP",
    frontCamera: "16MP",
    os: "Android 13 / MIUI 14"
  },
    colors: ["Black", "White", "Aurora Purple"],
    description: "Redmi Note 13 Pro+ is a premium mid-ranger with a 200MP camera, powerful Dimensity chip, and 120W charging.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 34,
    name: "Redmi Note 13 Pro",
    brand: "Xiaomi",
    price: 13999,
    oldPrice: 16999,
    image: "images/Xiaomi/Xiaomi-Redmi-Note-13-Pro-4G.webp",
    specs: ["Helio G99", "8GB RAM", "256GB", "4G"],
    badge: "Sale",
    badgeType: "sale",
    category: "xiaomi",
    //Details:
    detailedSpecs: {
    processor: "Helio G99",
    ram: "8GB / 12GB",
    storage: "128GB / 256GB",
    network: "4G",
    screen: "6.67\" AMOLED",
    battery: "5000mAh",
    camera: "200MP + 8MP + 2MP",
    frontCamera: "16MP",
    os: "Android 13 / MIUI 14"
  },
    colors: ["Black", "Blue", "Purple"],
    description: "Redmi Note 13 Pro offers a 200MP camera and a large AMOLED display at a great mid-range price.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 35,
    name: "POCO X6 Pro",
    brand: "Xiaomi",
    price: 14999,
    oldPrice: 17999,
    image: "images/Xiaomi/poco-x6-pro-2.webp",
    specs: ["Dimensity 8300", "12GB RAM", "512GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "xiaomi",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 8300 Ultra",
    ram: "8GB / 12GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.67\" AMOLED",
    battery: "5000mAh",
    camera: "64MP + 8MP + 2MP",
    frontCamera: "16MP",
    os: "Android 14 / HyperOS"
  },
    colors: ["Black", "Gray", "Yellow"],
    description: "POCO X6 Pro is a performance beast with the powerful Dimensity 8300 chip, ideal for mobile gaming.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 36,
    name: "POCO X6",
    brand: "Xiaomi",
    price: 11999,
    oldPrice: 14999,
    image: "images/Xiaomi/poco-x6-pro-2.webp",
    specs: ["Snapdragon 7s Gen 2", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "xiaomi",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 7s Gen 2",
    ram: "8GB / 12GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.67\" AMOLED",
    battery: "5100mAh",
    camera: "64MP + 8MP + 2MP",
    frontCamera: "16MP",
    os: "Android 13 / MIUI 14"
  },
    colors: ["Black", "White", "Blue"],
    description: "POCO X6 is a solid 5G phone with the Snapdragon 7s Gen 2 and a high-resolution AMOLED display.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },

  // ===== OPPO =====
  {
    id: 37,
    name: "OPPO Find X7 Ultra",
    brand: "OPPO",
    price: 48999,
    oldPrice: 56999,
    image: "images/oppo/Oppo-Find-X7-Ultra-1.webp",
    specs: ["Snapdragon 8 Gen 3", "16GB RAM", "512GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "OPPO",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 3",
    ram: "12GB / 16GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.82\" LTPO AMOLED",
    battery: "5000mAh",
    camera: "50MP Quad-Camera System",
    frontCamera: "32MP",
    os: "Android 14 / ColorOS 14"
  },
    colors: ["Black", "Blue", "Sepia Brown"],
    description: "OPPO Find X7 Ultra is a top-tier flagship with Snapdragon 8 Gen 3 and an advanced Quad-Camera system tuned by Hasselblad.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 38,
    name: "OPPO Reno 11 Pro",
    brand: "OPPO",
    price: 22999,
    oldPrice: 26999,
    image: "images/oppo/Oppo-Reno11-Pro-5G.webp",
    specs: ["Dimensity 8200", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "OPPO",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 8200",
    ram: "12GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.7\" AMOLED",
    battery: "4600mAh",
    camera: "50MP + 32MP + 8MP",
    frontCamera: "32MP",
    os: "Android 14 / ColorOS 14"
  },
    colors: ["Black", "White", "Green"],
    description: "OPPO Reno 11 Pro is a portrait expert, featuring a fast Dimensity 8200 chip and a sleek, modern design.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 39,
    name: "OPPO Reno 11",
    brand: "OPPO",
    price: 17999,
    oldPrice: 19999,
    image: "images/oppo/Oppo-A78-4G.webp",
    specs: ["Dimensity 7050", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "OPPO",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 7050",
    ram: "8GB / 12GB",
    storage: "256GB",
    network: "5G",
    screen: "6.7\" AMOLED",
    battery: "5000mAh",
    camera: "50MP + 32MP + 8MP",
    frontCamera: "32MP",
    os: "Android 14 / ColorOS 14"
  },
    colors: ["Black", "Green", "Blue"],
    description: "OPPO Reno 11 delivers reliable 5G performance and a versatile camera setup with the Dimensity 7050 processor.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 40,
    name: "oppo A60",
    brand: "OPPO",
    price: 10300,
    oldPrice: 10500,
    image: "images/oppo/Oppo-A60.webp",
    specs: ["Snapdragon 680", "8GB RAM", "256GB", "4G"],
    badge: "New",
    badgeType: "new",
    category: "OPPO",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 680",
    ram: "8GB",
    storage: "128GB / 256GB",
    network: "4G",
    screen: "6.67\" IPS LCD",
    battery: "5000mAh",
    camera: "50MP Dual Camera",
    frontCamera: "8MP",
    os: "Android 14 / ColorOS 14"
  },
    colors: ["Midnight Purple", "Ripple Blue"],
    description: "The OPPO A60 is a budget-friendly option with a large display and a massive 5000mAh battery for all-day use.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 41,
    name: "oppo reno 14",
    brand: "OPPO",
    price: 27000,
    oldPrice: 27200,
    image: "images/oppo/Oppo-Reno-14.webp",
    specs: ["Dimensity 8200", "12GB RAM", "256GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "OPPO",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 8200",
    ram: "12GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.7\" AMOLED",
    battery: "4600mAh",
    camera: "50MP Triple Camera",
    frontCamera: "32MP",
    os: "Android / ColorOS"
  },
    colors: ["Black", "Blue", "Gold"],
    description: "OPPO Reno 14 provides high-performance and fast charging with its Dimensity 8200 chip and a focus on camera quality.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 42,
    name: "OPPO A98",
    brand: "OPPO",
    price: 15999,
    oldPrice: 19999,
    image: "images/oppo/613viuxk6VL._AC_SL1042_.jpg",
    specs: ["Snapdragon 695", "8GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "OPPO",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 695 5G",
    ram: "8GB",
    storage: "256GB",
    network: "5G",
    screen: "6.72\" IPS LCD",
    battery: "5000mAh",
    camera: "64MP + 2MP + 2MP",
    frontCamera: "32MP",
    os: "Android 13 / ColorOS 13.1"
  },
    colors: ["Cool Black", "Dreamy Blue"],
    description: "OPPO A98 is a reliable mid-range phone offering 5G connectivity, a 64MP camera, and a large 5000mAh battery.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 43,
    name: "oppo A78 ",
    brand: "OPPO",
    price: 10500,
    oldPrice: null,
    image: "images/oppo/Oppo-A78-4G.webp",
    specs: ["Snapdragon 680", "8GB RAM", "256GB", "4G"],
    badge: "New",
    badgeType: "new",
    category: "OPPO",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 680",
    ram: "8GB",
    storage: "128GB / 256GB",
    network: "4G",
    screen: "6.43\" AMOLED",
    battery: "5000mAh",
    camera: "50MP Dual Camera",
    frontCamera: "8MP",
    os: "Android 13 / ColorOS 13.1"
  },
    colors: ["Aqua Green", "Misty Black"],
    description: "OPPO A78 offers a vibrant AMOLED display and a 50MP camera system, providing a great user experience at an entry-level price.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 44,
    name: "oppo A3 ",
    brand: "OPPO",
    price: 9600,
    oldPrice: 9900,
    image: "images/oppo/OPPO-A3-1.webp",
    specs: ["Dimensity 6300", "8GB RAM", "256GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "OPPO",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 6300",
    ram: "8GB",
    storage: "256GB",
    network: "5G",
    screen: "6.67\" IPS LCD",
    battery: "5100mAh",
    camera: "50MP Dual Camera",
    frontCamera: "8MP",
    os: "Android 14 / ColorOS 14"
  },
    colors: ["Blue", "Starry Black"],
    description: "OPPO A3 is a new entry-level 5G phone with a durable battery and a capable Dimensity 6300 processor.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 45,
    name: "OPPO A5",
    brand: "OPPO",
    price: 7600,
    oldPrice: 7800,
    image: "images/oppo/Oppo-A5-4G.webp",
    specs: ["Dimensity 6020", "12GB RAM", "512GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "OPPO",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 6020",
    ram: "12GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.72\" IPS LCD",
    battery: "5000mAh",
    camera: "50MP Dual Camera",
    frontCamera: "8MP",
    os: "Android 14 / ColorOS 14"
  },
    colors: ["Black", "Violet", "Green"],
    description: "OPPO A1s offers a huge 512GB storage option and 5G connectivity with the efficient Dimensity 6020 chipset.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },

  // ===== REALME =====
  {
    id: 46,
    name: "Realme GT 5 Pro",
    brand: "Realme",
    price: 26999,
    oldPrice: 32999,
    image: "images/realme/Realme-GT-5-Pro.webp",
    specs: ["Snapdragon 8 Gen 3", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "Realme",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 3",
    ram: "12GB / 16GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.78\" AMOLED",
    battery: "5400mAh",
    camera: "50MP Triple Camera",
    frontCamera: "32MP",
    os: "Android 14 / Realme UI 5.0"
  },
    colors: ["Black", "White", "Orange (Leather)"],
    description: "Realme GT 5 Pro is a performance flagship featuring the Snapdragon 8 Gen 3, a large 5400mAh battery, and fast charging.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 47,
    name: "Realme 12 Pro+",
    brand: "Realme",
    price: 16999,
    oldPrice: 19999,
    image: "images/realme/realme12-pro-plus.webp",
    specs: ["Snapdragon 7s Gen 2", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "Realme",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 7s Gen 2",
    ram: "8GB / 12GB",
    storage: "128GB / 256GB",
    network: "5G",
    screen: "6.7\" AMOLED",
    battery: "5000mAh",
    camera: "50MP + 64MP (Periscope) + 8MP",
    frontCamera: "32MP",
    os: "Android 14 / Realme UI 5.0"
  },
    colors: ["Submarine Blue", "Navigator Beige", "Explorer Red"],
    description: "Realme 12 Pro+ features a premium design and an advanced camera system with a 3x Periscope Telephoto lens.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 48,
    name: "Realme C53",
    brand: "Realme",
    price: 7999,
    oldPrice: 9999,
    image: "images/realme/download.jpg",
    specs: ["Helio G88", "8GB RAM", "128GB", "4G"],
    badge: "Sale",
    badgeType: "sale",
    category: "Realme",
    //Details:
    detailedSpecs: {
    processor: "Helio G88",
    ram: "6GB / 8GB",
    storage: "128GB / 256GB",
    network: "4G",
    screen: "6.74\" IPS LCD",
    battery: "5000mAh",
    camera: "50MP Dual Camera",
    frontCamera: "8MP",
    os: "Android 13 / Realme UI T"
  },
    colors: ["Champion Gold", "Mighty Black"],
    description: "Realme C53 is a great entry-level phone with a massive 5000mAh battery and a high-resolution 50MP camera.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },

  // ===== ONEPLUS =====
  {
    id: 49,
    name: "OnePlus 12",
    brand: "OnePlus",
    price: 38999,
    oldPrice: 45999,
    image: "images/OnePlus/OnePlus-12-3-600x600.webp",
    specs: ["Snapdragon 8 Gen 3", "16GB RAM", "512GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "ONEPLUS",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 3",
    ram: "12GB / 16GB / 24GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.82\" LTPO AMOLED",
    battery: "5400mAh",
    camera: "50MP Triple Camera",
    frontCamera: "32MP",
    os: "Android 14 / OxygenOS 14"
  },
    colors: ["Flowy Emerald", "Silky Black"],
    description: "OnePlus 12 is a powerful flagship with Snapdragon 8 Gen 3, a large 5400mAh battery, and 100W fast charging.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 50,
    name: "OnePlus 11",
    brand: "OnePlus",
    price: 29999,
    oldPrice: 34999,
    image: "images/OnePlus/OnePlus-11-600x600.webp",
    specs: ["Snapdragon 8 Gen 2", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "ONEPLUS",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 2",
    ram: "8GB / 16GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.7\" LTPO AMOLED",
    battery: "5000mAh",
    camera: "50MP + 32MP + 48MP",
    frontCamera: "16MP",
    os: "Android 13 / OxygenOS 13"
  },
    colors: ["Titan Black", "Eternal Green"],
    description: "OnePlus 11 offers fast performance with the Snapdragon 8 Gen 2 and a great 50MP camera system tuned by Hasselblad.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 51,
    name: "OnePlus Nord 3",
    brand: "OnePlus",
    price: 18999,
    oldPrice: 22999,
    image: "images/OnePlus/download.jpg",
    specs: ["Dimensity 9000", "16GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "ONEPLUS",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 9000",
    ram: "8GB / 16GB",
    storage: "128GB / 256GB",
    network: "5G",
    screen: "6.74\" AMOLED",
    battery: "5000mAh",
    camera: "50MP + 8MP + 2MP",
    frontCamera: "16MP",
    os: "Android 13 / OxygenOS 13.1"
  },
    colors: ["Misty Green", "Tempest Gray"],
    description: "OnePlus Nord 3 is a fast mid-range phone with the powerful Dimensity 9000 chip and a smooth AMOLED display.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },

  // ===== HONOR =====
  {
    id: 52,
    name: "Honor Magic 6 Pro",
    brand: "Honor",
    price: 42999,
    oldPrice: 49999,
    image: "images/honor/Honor-Magic-6-Pro-600x600.webp",
    specs: ["Snapdragon 8 Gen 3", "12GB RAM", "512GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "HONOR",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8 Gen 3",
    ram: "12GB / 16GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.8\" LTPO OLED",
    battery: "5600mAh",
    camera: "50MP Triple Camera",
    frontCamera: "50MP + TOF 3D",
    os: "Android 14 / MagicOS 8"
  },
    colors: ["Black", "Green", "White", "Purple"],
    description: "Honor Magic 6 Pro is a performance giant with a Snapdragon 8 Gen 3 chip, advanced camera technology, and a huge 5600mAh battery.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 53,
    name: "Honor 90",
    brand: "Honor",
    price: 15999,
    oldPrice: 19999,
    image: "images/honor/Honor-90.webp",
    specs: ["Snapdragon 7 Gen 1", "12GB RAM", "512GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "HONOR",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 7 Gen 1 Accelerated Edition",
    ram: "8GB / 12GB",
    storage: "256GB / 512GB",
    network: "5G",
    screen: "6.7\" AMOLED",
    battery: "5000mAh",
    camera: "200MP + 12MP + 2MP",
    frontCamera: "50MP",
    os: "Android 13 / MagicOS 7.1"
  },
    colors: ["Diamond Silver", "Emerald Green", "Midnight Black"],
    description: "Honor 90 focuses on photography with its massive 200MP main camera and high-resolution 50MP front camera.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },

  // ===== VIVO =====
  {
    id: 54,
    name: "Vivo X100 Pro",
    brand: "Vivo",
    price: 46999,
    oldPrice: 54999,
    image: "images/vivo/Vivo-X100-Pro-4-600x600.webp",
    specs: ["Dimensity 9300", "16GB RAM", "512GB", "5G"],
    badge: "New",
    badgeType: "new",
    category: "Vivo",
    //Details:
    detailedSpecs: {
    processor: "Dimensity 9300",
    ram: "12GB / 16GB",
    storage: "256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.78\" AMOLED",
    battery: "5400mAh",
    camera: "50MP Triple Camera (Zeiss Optics)",
    frontCamera: "32MP",
    os: "Android 14 / Funtouch OS 14"
  },
    colors: ["Black", "White", "Blue", "Orange"],
    description: "Vivo X100 Pro is a photography flagship with the powerful Dimensity 9300 chip and a premium Zeiss-tuned camera system.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 55,
    name: "Vivo V29",
    brand: "Vivo",
    price: 19999,
    oldPrice: 23999,
    image: "images/vivo/Vivo-V29-5G.webp",
    specs: ["Snapdragon 778G", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "Vivo",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 778G+ 5G",
    ram: "8GB / 12GB",
    storage: "128GB / 256GB",
    network: "5G",
    screen: "6.78\" AMOLED",
    battery: "4600mAh",
    camera: "50MP + 8MP + 2MP",
    frontCamera: "50MP AF",
    os: "Android 13 / Funtouch OS 13"
  },
    colors: ["Black", "Blue", "Purple", "Red"],
    description: "Vivo V29 is a stylish mid-range phone known for its excellent camera performance, especially for portraits, and its unique design.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },

  // ===== GOOGLE PIXEL =====
  {
    id: 56,
    name: "Google Pixel 8 Pro",
    brand: "Google",
    price: 52999,
    oldPrice: 62999,
    image: "images/google/Google-Pixel-8-Pro-3.webp",
    specs: ["Tensor G3", "12GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "GOOGLE PIXEL",
    //Details:
    detailedSpecs: {
    processor: "Google Tensor G3",
    ram: "12GB",
    storage: "128GB / 256GB / 512GB / 1TB",
    network: "5G",
    screen: "6.7\" LTPO OLED",
    battery: "5050mAh",
    camera: "50MP + 48MP + 48MP",
    frontCamera: "10.5MP",
    os: "Android 14"
  },
    colors: ["Obsidian", "Porcelain", "Bay"],
    description: "Google Pixel 8 Pro is Google's top-tier phone, offering the best of AI with the Tensor G3 chip and a revolutionary camera system.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 57,
    name: "Google Pixel 8",
    brand: "Google",
    price: 42999,
    oldPrice: 49999,
    image: "images/google/Google-Pixel-8-2.webp",
    specs: ["Tensor G3", "8GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "GOOGLE PIXEL",
    //Details:
    detailedSpecs: {
    processor: "Google Tensor G3",
    ram: "8GB",
    storage: "128GB / 256GB",
    network: "5G",
    screen: "6.2\" OLED",
    battery: "4575mAh",
    camera: "50MP + 12MP",
    frontCamera: "10.5MP",
    os: "Android 14"
  },
    colors: ["Obsidian", "Hazel", "Rose"],
    description: "Google Pixel 8 is the perfect blend of performance, design, and intelligent AI features, powered by the Tensor G3 chip.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 58,
    name: "Google Pixel 7a",
    brand: "Google",
    price: 26999,
    oldPrice: 32999,
    image: "images/google/Google-Pixel-7a-600x600.webp",
    specs: ["Tensor G2", "8GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "GOOGLE PIXEL",
    //Details:
    detailedSpecs: {
    processor: "Google Tensor G2",
    ram: "8GB",
    storage: "128GB",
    network: "5G",
    screen: "6.1\" OLED",
    battery: "4385mAh",
    camera: "64MP + 13MP",
    frontCamera: "13MP",
    os: "Android 13"
  },
    colors: ["Charcoal", "Snow", "Sea"],
    description: "Google Pixel 7a offers flagship camera and AI features at a mid-range price point, powered by the Tensor G2 chip.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },

  // ===== NOTHING =====
  {
    id: 59,
    name: "Nothing Phone (2)",
    brand: "Nothing",
    price: 26999,
    oldPrice: 32999,
    image: "images/nothing/Nothing-Phone-2-2.webp",
    specs: ["Snapdragon 8+ Gen 1", "12GB RAM", "256GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "NOTHING",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 8+ Gen 1",
    ram: "8GB / 12GB",
    storage: "128GB / 256GB / 512GB",
    network: "5G",
    screen: "6.7\" OLED",
    battery: "4700mAh",
    camera: "50MP + 50MP",
    frontCamera: "32MP",
    os: "Android 13 / Nothing OS 2.5"
  },
    colors: ["Dark Gray", "White"],
    description: "Nothing Phone (2) is a unique phone with the innovative Glyph Interface and high-end Snapdragon 8+ Gen 1 performance.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
  {
    id: 60,
    name: "Nothing Phone (1)",
    brand: "Nothing",
    price: 19999,
    oldPrice: 24999,
    image: "images/nothing/Nothing-Phone-1.webp",
    specs: ["Snapdragon 778G+", "8GB RAM", "128GB", "5G"],
    badge: "Sale",
    badgeType: "sale",
    category: "NOTHING",
    //Details:
    detailedSpecs: {
    processor: "Snapdragon 778G+ 5G",
    ram: "8GB / 12GB",
    storage: "128GB / 256GB",
    network: "5G",
    screen: "6.55\" OLED",
    battery: "4500mAh",
    camera: "50MP + 50MP",
    frontCamera: "16MP",
    os: "Android 12 / Nothing OS 2.5"
  },
    colors: ["Black", "White"],
    description: "Nothing Phone (1) launched with the unique transparent design and Glyph Interface, offering a solid mid-range experience.",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    delivery: "2-3 Days",
    freeShipping: true
  },
]
